CUDA_VISIBLE_DEVICES=0 python ./LLaMA-Effcient-Tuning/src/train_bash.py \
    --stage sft \
    --model_name_or_path Qwen/Qwen-14B \
    --use_fast_tokenizer True \
    --do_train \
    --dataset_dir ./LLaMA-Effcient-Tuning/data_for_fintune \
    --dataset nips_add_v7 \
    --template default \
    --finetuning_type lora \
    --lora_rank 8 \
    --lora_target "c_attn","c_proj" \
    --output_dir ./output \
    --overwrite_output_dir True \
    --overwrite_cache \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 1.0 \
    --plot_loss \
    --bf16